# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20171124_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='client_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
