# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_transaction_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
