# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_transaction_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
