# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_transaction_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name=b'Date'),
        ),
    ]
