# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20171202_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product_logo',
            field=models.FileField( upload_to=b''),
        ),
    ]
