# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_transaction_product_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_logo',
            field=models.FileField(default=b'', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=b'', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rate',
            field=models.IntegerField(default=b'', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_cost',
            field=models.IntegerField(default=b'', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
