# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 08:12
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20171202_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(default=b'', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('rate', models.IntegerField(default=b'', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('total_cost', models.IntegerField(default=b'', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField(default=datetime.date.today, verbose_name=b'Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_logo',
            field=models.FileField(upload_to=b''),
        ),
    ]
