# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20171204_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_approved',
            new_name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_rejected',
        ),
    ]
