# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20171204_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='product_name',
            new_name='client_name',
        ),
    ]
