# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20171205_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='client_name',
            new_name='category_name',
        ),
    ]
