# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_remove_transaction_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_favorite',
            new_name='is_approved',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
