# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_auto_20171212_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_favorite',
            new_name='is_approved',
        ),
    ]
